owasp.attack.csrf=https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)
owasp.attack.insecureDirectObjectReferences=https://www.owasp.org/index.php/Testing_for_Insecure_Direct_Object_References_(OTG-AUTHZ-004)
owasp.attack.securityMisconfiguration=https://www.owasp.org/index.php/Testing_for_configuration_management
owasp.attack.sqli=https://www.owasp.org/index.php/SQL_Injection
owasp.attack.sessionManagement=https://www.owasp.org/index.php/Testing_for_Session_Management
owasp.attack.xxe=https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Processing
owasp.attack.xss=https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)
owasp.defend.unvalidatedRedirectsAndForwards=https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html
owasp.otg.buslogic.001 = https://www.owasp.org/index.php/Test_business_logic_data_validation_(OTG-BUSLOGIC-001)
owasp.top10.failureToRestrictUrlAccess=https://www.owasp.org/index.php/Top_10_2010-A8-Failure_to_Restrict_URL_Access
owasp.top10.insecureCryptoStorage=https://www.owasp.org/index.php/Top_10_2010-A7-Insecure_Cryptographic_Storage
owasp.mobile.m1.improperCredentialUsage=https://owasp.org/www-project-mobile-top-10/2023-risks/m1-improper-credential-usage
owasp.mobile.m3.insecureAuthentication=https://owasp.org/www-project-mobile-top-10/2023-risks/m3-insecure-authentication-authorization
owasp.mobile.m2.inadequateSupplyChain=https://owasp.org/www-project-mobile-top-10/2023-risks/m2-inadequate-supply-chain-security
owasp.mobile.m4.insufficientInputValidation=https://owasp.org/www-project-mobile-top-10/2023-risks/m4-insufficient-input-output-validation
owasp.mobile.m5.insecureCommunication=https://owasp.org/www-project-mobile-top-10/2023-risks/m5-insecure-communication
owasp.mobile.m6.inadequatePrivacyControls=https://owasp.org/www-project-mobile-top-10/2023-risks/m6-inadequate-privacy-controls
owasp.mobile.m7.insufficientBinaryProtections=https://owasp.org/www-project-mobile-top-10/2023-risks/m7-insufficient-binary-protections
owasp.mobile.m8.securityMisconfiguration=https://owasp.org/www-project-mobile-top-10/2023-risks/m8-security-misconfiguration
owasp.mobile.m9.insecureDataStorage=https://owasp.org/www-project-mobile-top-10/2023-risks/m9-insecure-data-storage
owasp.mobile.m10.insufficientCryptography=https://owasp.org/www-project-mobile-top-10/2023-risks/m10-insufficient-cryptography
